# Generated by Django 4.2.2 on 2023-06-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='remark',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
    ]
