# Generated by Django 4.2.2 on 2023-06-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='产品编号')),
                ('name', models.CharField(max_length=64, verbose_name='产品名称')),
                ('barcode', models.CharField(blank=True, max_length=32, null=True, verbose_name='条码')),
                ('spec', models.CharField(blank=True, max_length=64, null=True, verbose_name='规格')),
                ('shelf_life_days', models.IntegerField(null=True, verbose_name='保质期天数')),
                ('purchase_price', models.FloatField(default=0, verbose_name='采购价')),
                ('retail_price', models.FloatField(default=0, verbose_name='零售价')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
            ],
        ),
    ]
