# Generated by Django 4.0.4 on 2023-06-26 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_test', '0003_goodscategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_set', to='erp_test.goodscategory', verbose_name='产品分类'),
        ),
    ]
